name: CI

on:
  push:
    branches:
      - "**"

jobs:

  test:
    permissions:
      contents: 'read'
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        version:
          - 1.20.14
          - 1.21.13
          - 1.22.9
          - 1.23.3

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Test
        run: |
          docker run \
            --rm \
            --volume "$(pwd):/src" \
            --workdir /src \
            golang:${{ matrix.version }}-bullseye go test -shuffle on -race ./...
